environment:
  matrix:


    # Python 2.6.6 is the latest Python 2.6 with a Windows installer
    # See: https://github.com/ogrisel/python-appveyor-demo/issues/10

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.1"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.1"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install cx_Freeze irc3"

build_script:
  - "python setup.py build_ext --inplace"

test_script:
  # Run the project tests
  # - "python tests/test_tgen.py"

after_test:
  # If tests are successful, create binary packages for the project.
  - "cd standalone"
  - "call build.bat"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: standalone\dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#